import { Inter, Purple_Purse } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

const pp_acma = Purple_Purse({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Sticky Cards Using ScrollTrigger",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn("text-white", pp_acma.className)}>
        <Navbar />
        <main className="mt-[20vh] min-h-screen">{children}</main>
      </body>
    </html>
  );
}
